#### Read a dataset into a dataframe

In [2]:
import pandas as pd

In [4]:
housing_data = pd.read_csv('house_prices.csv')
housing_data.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

#### Checking the dataframe column names

In [7]:
housing_data.columns

Index(['area_type', 'availability', 'location', 'size', 'society',
       'total_sqft', 'bath', 'balcony', 'price'],
      dtype='object')

#### Subsetting the dataframe

In [12]:
housing_data_one = housing_data[['location', 'size', 'total_sqft', 'bath', 'price']]

In [14]:
housing_data.head(2)

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00

In [16]:
housing_data_one.head(2)

                   location       size total_sqft  bath   price
0  Electronic City Phase II      2 BHK       1056   2.0   39.07
1          Chikka Tirupathi  4 Bedroom       2600   5.0  120.00

In [18]:
housing_data.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

#### Featuring Engineering

In [26]:
housing_data_one.head()

                   location       size total_sqft  bath   price
0  Electronic City Phase II      2 BHK       1056   2.0   39.07
1          Chikka Tirupathi  4 Bedroom       2600   5.0  120.00
2               Uttarahalli      3 BHK       1440   2.0   62.00
3        Lingadheeranahalli      3 BHK       1521   3.0   95.00
4                  Kothanur      2 BHK       1200   2.0   51.00

In [31]:
housing_data_one['size'].head(30)

0         2 BHK
1     4 Bedroom
2         3 BHK
3         3 BHK
4         2 BHK
5         2 BHK
6         4 BHK
7         4 BHK
8         3 BHK
9     6 Bedroom
10        3 BHK
11    4 Bedroom
12        2 BHK
13        2 BHK
14    3 Bedroom
15        2 BHK
16        3 BHK
17        3 BHK
18        3 BHK
19        2 BHK
20        1 BHK
21        3 BHK
22    4 Bedroom
23        3 BHK
24         1 RK
25        3 BHK
26        2 BHK
27        3 BHK
28        2 BHK
29        3 BHK
Name: size, dtype: object

In [29]:
# Checking the unique elements the size column
housing_data_one['size'].unique()

array(['2 BHK', '4 Bedroom', '3 BHK', '4 BHK', '6 Bedroom', '3 Bedroom',
       '1 BHK', '1 RK', '1 Bedroom', '8 Bedroom', '2 Bedroom',
       '7 Bedroom', '5 BHK', '7 BHK', '6 BHK', '5 Bedroom', '11 BHK',
       '9 BHK', nan, '9 Bedroom', '27 BHK', '10 Bedroom', '11 Bedroom',
       '10 BHK', '19 BHK', '16 BHK', '43 Bedroom', '14 BHK', '8 BHK',
       '12 Bedroom', '13 BHK', '18 Bedroom'], dtype=object)

In [ ]:
# Create a column 'bedroom'
# The bedroom column is going to have numbers

In [35]:
# Remove missing values
housing_data_one.isnull().sum()

location       1
size          16
total_sqft     0
bath          73
price          0
dtype: int64

In [39]:
housing_data_one = housing_data_one.dropna()

In [41]:
housing_data_one.isnull().sum()

location      0
size          0
total_sqft    0
bath          0
price         0
dtype: int64

In [33]:
housing_data_one['size'].apply(lambda x: int(x.split(' ')[0]))

AttributeError: 'float' object has no attribute 'split'

In [45]:
housing_data_one['bedroom'] = housing_data_one['size'].apply(lambda x: int(x.split(' ')[0]))

/var/folders/dy/cw3jgpfj77gbfn_1svh5cj4c0000gn/T/ipykernel_6699/3868276186.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  housing_data_one['bedroom'] = housing_data_one['size'].apply(lambda x: int(x.split(' ')[0]))

In [47]:
housing_data_one.head()

                   location       size total_sqft  bath   price  bedroom
0  Electronic City Phase II      2 BHK       1056   2.0   39.07        2
1          Chikka Tirupathi  4 Bedroom       2600   5.0  120.00        4
2               Uttarahalli      3 BHK       1440   2.0   62.00        3
3        Lingadheeranahalli      3 BHK       1521   3.0   95.00        3
4                  Kothanur      2 BHK       1200   2.0   51.00        2

## EXPLORE TOTAL_SQFT FEATURE ##

In [ ]:
housing_data_two = housing_data_one.copy