### Analysis of Water Potability

In [ ]:
# Read the data into a dataframe
# I will import a data analysis package

In [3]:
import pandas as pd # Importing Pandas

In [7]:
data_water = pd.read_csv('water_potability.csv') # Reading a dataset

In [9]:
data_water.head() # The first 5 Rows

,ph,Hardness,Solids,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity,Potability
0,NaN,204.890455,20791.318981,7.300212,368.516441,564.308654,10.379783,86.990970,2.963135,0
1,3.716080,129.422921,18630.057858,6.635246,NaN,592.885359,15.180013,56.329076,4.500656,0
2,8.099124,224.236259,19909.541732,9.275884,NaN,418.606213,16.868637,66.420093,3.055934,0
3,8.316766,214.373394,22018.417441,8.059332,356.886136,363.266516,18.436524,100.341674,4.628771,0
4,9.092223,181.101509,17978.986339,6.546600,310.135738,398.410813,11.558279,31.997993,4.075075,0

### Variables & Data Types

In [ ]:
# Variables are containers
# Data Types are values

In [16]:
print(5)

5

In [18]:
print("Adele")

Adele

In [22]:
name = "Adele" # Variable containing Adele

In [24]:
print(name)

Adele

In [26]:
my_name = "Pablo" # Variable containing my name
print(my_name)

Pablo

In [28]:
fav_number = 26 # Variable containing a number
print(fav_number)

26

In [30]:
my_name = ("Pablo")

In [32]:
print(my_name)

Pablo

In [34]:
type(my_name)

str

### Naming & Using Variables

In [37]:
# Rules and guidelines for using and naming variables

In [ ]:
# 1. Variables can contain only letters, numbers,
# and underscores. 
# You can't start a variable with a number

In [39]:
my_name1 = "Peter"

In [41]:
_name = "Pablo"

In [45]:
26_name = "Pablo"

SyntaxError: invalid decimal literal (1379398946.py, line 1)

In [ ]:
# 2. Spaces are not allowed in variable names
# Underscores can be used

In [47]:
my name = "Pablo"

SyntaxError: invalid syntax (2471611087.py, line 1)

In [ ]:
# 3. Avoid using Python keywords and function names
# as variable names

In [49]:
num = [23,45,67]

In [51]:
sum(num)

135

In [53]:
sum = 26

In [55]:
sum(num)

TypeError: 'int' object is not callable

In [59]:
help("keywords")

Here is a list of the Python keywords.  Enter any keyword to get more help.

False               class               from                or
None                continue            global              pass
True                def                 if                  raise
and                 del                 import              return
as                  elif                in                  try
assert              else                is                  while
async               except              lambda              with
await               finally             nonlocal            yield
break               for                 not

In [61]:
print(sum)

26

In [63]:
del sum

In [65]:
sum(num)

135

#### String Methods

In [5]:
name = "Pablo" # A variable containing a string

In [7]:
print(name)

Pablo

In [13]:
job_pablo = "Data Science Educator" # Another variable containing a series of characters

In [11]:
type(job_pablo) # The type function

str

In [15]:
dir(job_pablo) # The dir function

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'removeprefix',
 'removesuffix',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',
 'zfill']

In [17]:
print(job_pablo)

Data Science Educator

In [19]:
print(job_pablo.upper()) # Using the upper string method

DATA SCIENCE EDUCATOR

In [23]:
?job_pablo.upper # The documentation for the upper method

Signature: job_pablo.upper()
Docstring: Return a copy of the string converted to uppercase.
Type:      builtin_function_or_method

In [25]:
?job_pablo.zfill # The documentation of the zfill method

Signature: job_pablo.zfill(width, /)
Docstring:
Pad a numeric string with zeros on the left, to fill a field of the given width.

The string is never truncated.
Type:      builtin_function_or_method

In [27]:
?job_pablo.split # The documentation of the split method

Signature: job_pablo.split(sep=None, maxsplit=-1)
Docstring:
Return a list of the substrings in the string, using sep as the separator string.

  sep
    The separator used to split the string.

    When set to None (the default value), will split on any whitespace
    character (including \n \r \t \f and spaces) and will discard
    empty strings from the result.
  maxsplit
    Maximum number of splits.
    -1 (the default value) means no limit.

Splitting starts at the front of the string and works to the end.

Note, str.split() is mainly useful for data that has been intentionally
delimited.  With natural text that includes punctuation, consider using
the regular expression module.
Type:      builtin_function_or_method

In [31]:
job_pablo.upper() # Using the upper method

'DATA SCIENCE EDUCATOR'

In [33]:
?job_pablo.replace # The documentation of the replace method

Signature: job_pablo.replace(old, new, count=-1, /)
Docstring:
Return a copy with all occurrences of substring old replaced by new.

  count
    Maximum number of occurrences to replace.
    -1 (the default value) means replace all occurrences.

If the optional argument count is given, only the first count occurrences are
replaced.
Type:      builtin_function_or_method

In [35]:
print(job_pablo)

Data Science Educator

In [45]:
job_pablo_update = job_pablo.replace('Educator', 'Instructor')

In [39]:
?job_pablo.index

Docstring:
S.index(sub[, start[, end]]) -> int

Return the lowest index in S where substring sub is found,
such that sub is contained within S[start:end].  Optional
arguments start and end are interpreted as in slice notation.

Raises ValueError when the substring is not found.
Type:      builtin_function_or_method

In [47]:
job_pablo_update.index('Instructor') # Using the index method

13

In [49]:
fav_num = 26 # A variable containing a number

In [51]:
dir(fav_num) # Method for a numerical datatype

['__abs__',
 '__add__',
 '__and__',
 '__bool__',
 '__ceil__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floor__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__le__',
 '__lshift__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__trunc__',
 '__xor__',
 'as_integer_ratio',
 'bit_count',
 'bit_length',
 'conjugate',
 'denominator',
 'from_bytes',
 'imag',
 'is_integer',
 'numerator',
 'real',
 'to_bytes']

#### Introduction to Lists

In [105]:
# Create a simple list
# This is a list of list
work_list = [
    ["Kpokpo", "Chioma", "Daddy's Girl"],
    ["Normal", "Aniekan", "Budding Data Scientist"],
    ["Not Sure", "Maryam", "Student"]
]

In [107]:
daddy_girl =  ["Kpokpo", "Chioma", "Daddy's Girl"] # A simple list

In [109]:
import pandas as pd # A data manipulation package

In [111]:
df = pd.DataFrame(work_list, columns=["Garri Type", "Name", "Profession"])

In [113]:
df

  Garri Type     Name              Profession
0     Kpokpo   Chioma            Daddy's Girl
1     Normal  Aniekan  Budding Data Scientist
2   Not Sure   Maryam                 Student

##### *Attributes of a list*

In [116]:
# It is mutable
# It is sequential 
# Use a pair of square brackets to create a list

In [118]:
print(daddy_girl)

['Kpokpo', 'Chioma', "Daddy's Girl"]

In [120]:
daddy_girl[1] = 'Ivy' # A list is mutable

In [122]:
daddy_girl

['Kpokpo', 'Ivy', "Daddy's Girl"]

In [124]:
dir(daddy_girl) # List methods

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [130]:
?daddy_girl.append

Signature: daddy_girl.append(object, /)
Docstring: Append object to the end of the list.
Type:      builtin_function_or_method

In [132]:
daddy_girl.append("BMW") # Append an elent to the end of the list

In [134]:
daddy_girl.append(10000)

In [136]:
daddy_girl

['Kpokpo', 'Ivy', "Daddy's Girl", 'BMW', 10000]

In [138]:
?daddy_girl.insert

Signature: daddy_girl.insert(index, object, /)
Docstring: Insert object before index.
Type:      builtin_function_or_method

In [140]:
daddy_girl.insert(1, 'David')

In [142]:
daddy_girl

['Kpokpo', 'David', 'Ivy', "Daddy's Girl", 'BMW', 10000]

In [148]:
daddy_girl.append("BMW") # Run this cell three times

In [150]:
daddy_girl

['Kpokpo', 'David', 'Ivy', "Daddy's Girl", 'BMW', 10000, 'BMW', 'BMW', 'BMW']

In [152]:
?daddy_girl.remove

Signature: daddy_girl.remove(value, /)
Docstring:
Remove first occurrence of value.

Raises ValueError if the value is not present.
Type:      builtin_function_or_method

In [154]:
?daddy_girl.pop

Signature: daddy_girl.pop(index=-1, /)
Docstring:
Remove and return item at index (default last).

Raises IndexError if list is empty or index is out of range.
Type:      builtin_function_or_method

In [156]:
daddy_girl

['Kpokpo', 'David', 'Ivy', "Daddy's Girl", 'BMW', 10000, 'BMW', 'BMW', 'BMW']

In [158]:
daddy_girl.remove('BMW')

In [160]:
daddy_girl

['Kpokpo', 'David', 'Ivy', "Daddy's Girl", 10000, 'BMW', 'BMW', 'BMW']

In [162]:
daddy_girl.pop()

'BMW'

In [164]:
daddy_girl

['Kpokpo', 'David', 'Ivy', "Daddy's Girl", 10000, 'BMW', 'BMW']

#### List Comprehension

In [166]:
# Use list comprehension to remove two elements at the same time

In [168]:
bm = ['BMW']

In [170]:
type(bm)

list

In [172]:
daddy_girl = [x for x in daddy_girl if x not in bm]

In [174]:
daddy_girl

['Kpokpo', 'David', 'Ivy', "Daddy's Girl", 10000]

In [176]:
num_list = [3,4,5,6] # Another example of list comprehension

In [178]:
[x ** 2 for x in num_list]

[9, 16, 25, 36]

In [180]:
for x in num_list:
    print(x ** 2)

9
16
25
36

In [60]:
list_numbers = [13,24,50]

In [62]:
list_numbers * 2

[13, 24, 50, 13, 24, 50]

In [64]:
import numpy as np

In [66]:
list_numbers_array = np.array(list_numbers)

In [70]:
list_numbers_array

array([13, 24, 50])

In [72]:
list_numbers_array * 2

array([ 26,  48, 100])

#### Numeric Data Types

In [2]:
# What we do with numbers:
# 1. Arithmetic Calculations
# 2. Store Measurements 
# 3. Work with Money
# 4. Track quantities

#### Numeric Data Types in Python

In [ ]:
# int - Whole Number
# float - Decimal

In [5]:
# ints and floats 
4

4

In [7]:
45 + 56

101

In [9]:
# + - / *
num = 101

In [11]:
num * 2

202

In [13]:
num - 100

1

In [17]:
num = num + 100

In [19]:
print(num)

201

In [21]:
5/2 # Division

2.5

In [23]:
5//2 # Floored division

2

In [27]:
5 % 2.9

2.1

#### Tuples

##### *Attributes of Tuples*

In [ ]:
# Immutable 
# Indexable
# Ordered 
# Heterogeneous 
# ()
# Duplicates

In [29]:
tuple_num = 45,56, # Creating a simple Tuple

In [31]:
print(tuple_num)

(45, 56)

In [33]:
num_tuple_1 = (34,89,99) # Creating a simple Tuple using brackets

In [35]:
num_tuple_1

(34, 89, 99)

#### Casting a list to a tuple

In [38]:
num_list = [34,56,78,'Gobir']

In [40]:
type(num_list)

list

In [42]:
num_list_tuple = tuple(num_list) # Casting

In [44]:
print(num_list_tuple)

(34, 56, 78, 'Gobir')

In [50]:
dir(num_list)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [52]:
dir(num_list_tuple)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'count',
 'index']

In [38]:
# Indexing a Tuple

In [56]:
num_list_tuple[1]

56

In [58]:
num_list_tuple[1] = 100 # Tuples are Immutable

TypeError: 'tuple' object does not support item assignment

In [78]:
num_tuple_1

(34, 89, 99)

#### Tuple Methods

In [41]:
?num_tuple_1.count

Signature: num_tuple_1.count(value, /)
Docstring: Return number of occurrences of value.
Type:      builtin_function_or_method

In [43]:
?num_tuple_1.index

Signature: num_tuple_1.index(value, start=0, stop=9223372036854775807, /)
Docstring:
Return first index of value.

Raises ValueError if the value is not present.
Type:      builtin_function_or_method

In [45]:
print(num_tuple_1)

(34, 89, 99)

In [47]:
num_tuple_1.index(99)

2

In [49]:
name_student = "Abdullahi"

In [55]:
type(num_list)

#### Python Dictionary

In [ ]:
# Attributes
# 1. Key Value Pairs
# 2. Key - Immutable, Value - Mutable 
# 3. The columns are used to map keys to values
# 4. It is ordered 
# 5. It is indexable 
# 6. The keys are unique
# 7. It is heterogeneous 
# 8. It is wrapped in curly braces - Done

In [57]:
curly_brace = {"Pablo": "Data Professional"} # Creating a Dictionary

In [4]:
curly_brace[0] # Dictionary values are accessible using keys not index positions

KeyError: 0

In [6]:
curly_brace['Pablo']

'Data Professional'

In [8]:
print(curly_brace)

{'Pablo': 'Data Professional'}

#### Game - Level 1: The Scroll of Records

Challenge:
Create a dictionary to store details of a lost scroll with the following keys:

title

year

author

#### Level 2: The Oracle's Inquiry

##### Challenge:
##### *The Oracle asks: What is the title of the scroll?*

#### Level 3: The Time Stone (Update the Year)

##### *Time travel updated the scroll’s year. Change your year*

#### Level 4: The Secret Key (Add a New Field)

##### *Add a key called location with the value "CoLab Archives"*

### Assignment

#### Submission deadline: 12th July, 11:59pm

#### *Task: Build a Student Profile with a Dictionary*

##### *Goal:*


##### *Learn how to create a dictionary, access its values, and update it — just like storing a row of data.*

##### *Instructions:*


##### *Create a dictionary named student_profile with the following keys and values:*

"name" → Your name

"age" → Your age

"country" → Your country

"course" → "Data Science"

Print out the dictionary.

Access and print the "name" and "course" values.

Update the "age" value to a new number.

Add a new key "score" with a value of 90.

Print out the final dictionary.